version: '3'
services:
  maxdb:
    image: maximo/db2
    hostname: maxdb
    environment:
    - CTGINST1_PASSWORD=changeit
    - CTGFENC1_PASSWORD=changeit
    - DASUSR1_PASSWORD=changeit
    - MAXIMO_PASSWORD=changeit
    networks:
    - maxnet
    privileged: true
    volumes:
    - maxdb76:/home/ctginst1/ctginst1
    - vardb2:/var/db2
  maxdmgr:
    image: maximo/maxdmgr
    hostname: maxdmgr
    ports:
    - 9043:9043
    environment:
    - DMGR_ADMIN_PASSWORD=changeit
    networks:
    - maxnet
  maxapps:
    image: maximo/maxapps
    hostname: maxapps
    environment:
    - DMGR_ADMIN_PASSWORD=changeit
    depends_on:
      - maxdmgr
      - maxweb
    networks:
    - maxnet
  maxweb:
    image: maximo/maxweb
    hostname: maxweb
    environment:
    - DMGR_ADMIN_PASSWORD=changeit
    ports:
    - 80:80
    depends_on:
      - maxdmgr
    networks:
    - maxnet
  maximo:
    image: maximo/maximo
    hostname: maximo
    environment:
    - DMGR_ADMIN_PASSWORD=changeit
    - DB_MAXIMO_PASSWORD=changeit
    - MXINTADM_PASSWORD=changeit
    - MAXADMIN_PASSWORD=changeit
    - MAXREG_PASSWORD=changeit
    depends_on:
     - maxdb
     - maxapps
     - maxweb
    networks:
    - maxnet
networks:
  maxnet:
volumes:
  maxdb76:
  vardb2:
  pae76:
